---
title: "Introduction"
---

The prevalence of gender discrimination in institutions such as educational, political and labor force etc, have been well documented and have gained the attention of the media space, CEO’s and world leaders. According to a 2016 report by OECD, gender-based discrimination in social institutions costs up to 12 trillion USD for the global economy. The report notes that the fight for gender equality should not be focused solely on areas of education, labor and health outcomes but on addressing, holistically, the root cause of the issue. 

Discrimination against women is a universal issue that is driven by discriminatory social institutions and reinforced by outdated cultural and religious values. Progress in achieving gender equality can improve maternal mortality rates, reduce fertility rates and improve the health and wellbeing of children- who are the most vulnerable in the population. Advances in gender equality have economic as well as political effects.Gender discrimination within the social institutions of developing and developed countries inhibits the opportunity of choice. The choice to participate or not participate in democratic processes, the choice to get an education (formal or informal), and in general the opportunity to make choices that will produce optimal satisfaction for an individual. 

The freedom of choice is one of the consequences of a democractic society. Democracy is defined as “a  government  in which the supreme power is vested in the people and exercised by them directly or indirectly through a system of representation usually involving periodically  held free elections”. According to Kittilson (2016), gender discrimination in the democratic process undermines the quality of deliberation, representation and legitimacy of the democratic process. A study by Beer (2009),  she examined the relationship between political regimes and gender equality. The results showed that countries with longer-term democracy and longer duration of women’s suffrage had higher proportions of female to male life expectancy, lower fertility rates and higher labour force participation rates, due to the ability to advance their interests through voting.

