---
title: "Literature Review"
---

As we have seen from current literature, there is an economic and political case for gender equality. According to a report from the European Institute of Gender Equality, a more gender equal EU would have strong, positive GDP impacts growing over time. The report states that by 2050, improving gender equality would lead to an increase in GDP per capita from 6.1 to 9.6% for the EU. This percentage increase translates to 1.2 trillion pounds for EU member states. In terms of employment, the report posits that improvements in gender equality would lead an additional 10.5 million jobs by 2050 - and this increase would be beneficial to both men and women. 

The authors of the report attest to the fact that estimated GDP impacts on member states depend on the level of gender equality between each state. The report asserts that member states with more room for improvement on the topic of gender equality have a lot to gain from that improvement. This goes to say that countries that have made giant strides in the area of gender equality have reaped the economics benefits associated with gender equality. Improved gender equality measures could also help address demographic challenges, such as addressing the ageing population. Previous research suggests that gender equality in education, labour market participation and a more balanced sharing of unpaid work between women and men is linked to higher fertility rates, which would lead to a larger population and an increase in long-term labour supply.

In the political field, Potts(2016) explores the correlation between democracy and happiness. He explains that people choose democracy because it allows them to indirectly through representation make decisions in government. Jacob believes that it is the element of choice that makes people happy. The opportunity to choose what you believe in and to engage in acts that give the most utility results in the happiness within liberal democracies. It is the lack of choice that is apparent in illberal democracies that is associated with gender inequality. Research in political science suggests that there is an observed difference in political behavior that stems from gender inequality normally called the gender gap. Kittilson (2016), reported that gender differences in voting and participation persist across democracies and there is a confluence of several interrelated factors (resources, economy, socialization and political context) that can affect political behavior. 

In addition to understanding the interrelated factors that affect political behavior, Kittilson found that women were more likely to be politically conservative in political ideology, party attachment and vote choice across most democracies. The realignment of political behavior towards the left for women can be seen mostly in industrial societies and maybe not in post-communist societies and developing countries. The alignment with leftist ideas, is believed by some scholars to stem from the higher levels of religiosity in women from those advanced societies. Researchers have also found that the sea change of in women’s entrance into the paid workforce in the post–World War II era may also account for this shift in some countries but does not fully explain the patterns in postcommunist countries. Furthermore, across Western European countries finds that women are significantly less likely to cast their vote for radical right parties than men even after controlling for a host of social, economic, and political variables. 

Potrafke and Cooray (2010) examined empirically the relationship between democracy and gender inequality in education. The authors posit that the more limited democracy, the greater the bias in educating girls and therefore the greater is gender inequality in education. They found that democracy facilitates gender equality through the mobilization of women and electoral accountability. Through the findings, they suggest that apart from decreasing the level of gender inequality in education and labor force participation, a lot of work has to be done by the government to eradicate culture, religion and/or its subsets that will discourage women from getting an education. Also, in less democratic countries, there is an absence of rule of law which contributes to the level of gender inequality within the institutions of that country. 

