---
title: "Conclusion and References"
---


##Conclusion 

The case for gender equality has been well documented in academic reports and blog posts.  It is an issue that negatively affects the life of women, men and countries. The authors of the OECD report argue the importance of holistically  addressing the root cause of gender inequality. It is important to note that political representation and societal expectations of women do not always align. To effectively address this, government officials must prioritize the elimination of normative gender expectations that minimize equality in daily life. 


### References
Beer, C., 2009. Democracy and gender equality. Studies in International Comparative Development 44, 212-227.
Johnston, Michael. (2018). Corruption and Democracy: Threats to Development, Opportunities for Reform. 
Potrafke, N. & Cooray, A. V. (2010). Absence of democracy and gender inequality in education. 6th Australasian Development Economics Workshop 2010 (pp. 1-30). Sydney: School of Economics and Finance, University of Western Sydney
Inglehart, R., Norris, P. and Welzel, C. (2018). Gender Equality and Democracy. [online] Available at: https://www.fd.unl.pt/docentes_docs/ma/tpb_MA_6187.pdf [Accessed 8 Dec. 2018].
Worldvaluessurvey.org. (2018). WVS Database. [online] Available at: http://www.worldvaluessurvey.org/WVSContents.jsp [Accessed 8 Dec. 2018].
Kittilson, M. (2018). Gender and Political Behavior. Retrieved from http://oxfordre.com/politics/view/10.1093/acrefore/9780190228637.001.0001/acrefore-9780190228637-e-71
Economic Benefits of Gender Equality in the EU. (2018). Retrieved from https://eige.europa.eu/gender-mainstreaming/policy-areas/economic-and-financial-affairs/economic-benefits-gender-equality
(2018). Retrieved from https://www.oecd.org/dev/development-gender/SIGI_cost_final.pdf
McBain, S. (2014). Gender inequality is costing the global economy trillions of dollars a year. Retrieved from https://www.newstatesman.com/economics/2014/02/gender-inequality-costing-global-economy-trillions-dollars-year
Potts, J. (2016). Democracy and Happiness: A True Correlation?. Journal Of Arts & Humanities, 5(3). Retrieved from https://www.theartsjournal.org/index.php/site/article/view/913/459





