---
title: "Methodology"
---

The World Values Survey (WVS), which began in 1981, consists of nationally representative surveys using a common questionnaire conducted in approximately 100 countries--which make up some 90 percent of the world’s population. The WVS has become the largest non-commercial, cross- national, time series investigation of human beliefs and values ever conducted.

 It is interesting to note that findings from the WVS indicates gender equality is not a consequence of democratization but it is part of a broader cultural change that is transforming industrialized societies with mass demands for increasingly democratic institutions. As a consequence of these results, I believe that higher levels of gender inequality are prevalent in countries that have a large population of its citizens uneducated/unschooled. Also, the large population of uneducated citizens within a country has an association with how undemocratic a country is. To this effect, I will be testing hypotheses that will prove the association between gender inequality, level of democracy, educational attainment and economic stability. 

##Hypothesis I: Individuals in more democratic countries have a comparatively high level of educational attainment enjoy greater levels of economic stability.  

For this hypothesis, I will conducting a linear regression method in two parts. In the first part, I would be testing the relationship between educational attainment and democracy. In this test, I am inferring education as the dependent variable and level of democracy as the independent variable. I believe that an efficient level of democracy predates the ability of a country to develop and maintain a strong educational institution. An efficient level of democracy is a system of government where the government officials can be held accountable by the electorates for their actions. An efficient level of democracy also ensures that the system of checks and balances is kept in check. The educational attainment “dependent” variable will be measured by V248 “highest educational level attained”  while the level of democracy will be measured by V141 “how democratically is this country being governed today”. 

The second part of the testing will be between economic stability and education. The level of economic stability in a country will dictate the amount of job opportunities and will attract foreign direct investment that can be helpful for the economy. The education will be the independent variable and economic stability will be the dependent variable. The economic stability will be measured by V188 “in the last 12 months, how often have your family gone without enough food to eat”. The more often a family can go without access to food which is a basic toolkit for survival indicates the absence of money and the presence of economic hardships within a country. 

##Hypothesis II: Individuals in more democratic countries have comparatively lower levels of gender inequality in the political field due to the higher levels of educational attainment.

The essence of this paper is to test that the level of gender inequality is affected by the level of democracy and thereby reinforced through the low levels of educational attainment in a country. I believe that there is a positive relationship between gender inequality in a country’s political fied and the level of democracy within that country. This is in line with the finding by Beer(2009) that countries with longer term democracy amongst other factors have higher labor force participation rates due to the ability to advance their interests through voting. Voting is the proxy for the level of democracy because it represents the ability of the citizens to have their voices heard in government.

For the second hypothesis, I will be regressing level of democracy on educational attainment. The level of democracy will be the the independent variable, measured by V141 “how democratically is this country being governed today”.  The dependent variable will be the level of educational attainment measured by V248 “highest educational level attained”. This is like the first hypothesis, just to prove the association that exists between educational attainment and level of democracy. Then I will regress level of democracy on gender inequality in the political field, this will be to establish the association and direction of association between the variables. Gender inequality will be the dependent variable for this regression, measured by V139- “women have the same rights as men”, while the independent variable will be level of democracy will be measured by by V141 - “how democratically is this country being governed today”. 


##Hypothesis III: individuals who live in countries where there is a norm around gender inequality in education tend to be unhappier. 

Following the reasoning of Jacob Potts (2016), where he explored the correlation between democracy and happiness states that the element of choice that is afforded by democracy makes people to be happy. Potts posits that the opportunity to choose what you believe in and to engage in acts that give the most utility results in the happiness within liberal democracies. The choice to engage with educational institutions in the form of getting a formal or informal education should correlate with the feeling of happiness if Potts’ assertion is correct. So, we will be regressing the dependent variable of happiness measured by  V10 - “feeling of happiness” with the independent variables for gender inequality in education will be measured by V52 - “a university education is more important for a boy than for a girl”.
